/**
 * Exercise Catalog
 * Curated database of user-selected exercises for hypertrophy training
 */

import type { CatalogExercise, GymType, MovementPattern, MuscleGroup } from './types';

/**
 * Complete exercise catalog - user-curated list covering all body parts
 */
export const EXERCISE_CATALOG: CatalogExercise[] = [
  // CHEST (10 exercises)
  {
    id: 'pec-deck',
    name: 'Pec Deck',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Chest up, shoulders depressed', 'Squeeze handles together', 'Control the stretch'],
  },
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Keep back firmly against pad', 'Press straight, not angled', 'Full range of motion'],
  },
  {
    id: 'smith-bench-press',
    name: 'Smith Machine Bench Press',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['smith_machine'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Neutral grip or slightly angled', 'Full depth stretch', 'Control the bar'],
  },
  {
    id: 'smith-incline-bench',
    name: 'Smith Machine Incline Bench Press',
    movementPattern: 'vertical_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    muscleBias: 'chest_upper',
    equipment: ['smith_machine'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Incline 45 degrees', 'Press in straight line', 'Controlled descent'],
  },
  {
    id: 'upper-chest-fly',
    name: 'Upper Chest Fly',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    muscleBias: 'chest_upper',
    equipment: ['cable'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Slight elbow bend', 'Bring hands together at midline', 'Squeeze at top'],
  },
  {
    id: 'incline-machine-press',
    name: 'Incline Machine Press',
    movementPattern: 'vertical_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    muscleBias: 'chest_upper',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Shoulders pinned back', 'Press in straight line', 'Controlled descent'],
  },
  {
    id: 'flat-db-press',
    name: 'Flat Dumbbell Press',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Dumbbells at chest level', 'Press straight up', 'Control descent'],
  },
  {
    id: 'incline-db-press',
    name: 'Incline Dumbbell Press',
    movementPattern: 'vertical_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    muscleBias: 'chest_upper',
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Incline bench 45 degrees', 'Press at angle', 'Full range of motion'],
  },
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'intermediate',
    techniqueCues: ['Shoulder-width grip', 'Lower to chest', 'Explosive press'],
  },
  {
    id: 'barbell-incline-press',
    name: 'Barbell Incline Press',
    movementPattern: 'vertical_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    muscleBias: 'chest_upper',
    equipment: ['barbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'intermediate',
    techniqueCues: ['Incline 45 degrees', 'Lower to upper chest', 'Explosive press'],
  },

  // LATS (6 exercises)
  {
    id: 'wide-grip-lat-pulldown',
    name: 'Wide Grip Lat Pulldown',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    muscleBias: 'lats_lower',
    equipment: ['cable', 'machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Chest up, shoulders depressed', 'Pull elbows down and back', 'Full stretch at top'],
  },
  {
    id: 'seated-chest-supported-lat-row',
    name: 'Seated Chest-Supported Lat Row Machine',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    muscleBias: 'lats_lower',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Chest against pad', 'Pull handles to body', 'Squeeze shoulder blades'],
  },
  {
    id: 'unilateral-single-arm-pulldown',
    name: 'Unilateral Single Arm Pulldown',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['One arm at a time', 'Pull elbow down', 'Full range of motion'],
  },
  {
    id: 'wide-grip-pullups',
    name: 'Wide Grip Pullups',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    muscleBias: 'lats_lower',
    equipment: ['bodyweight'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'intermediate',
    techniqueCues: ['Wide grip', 'Pull chin over bar', 'Control descent'],
  },
  {
    id: 'close-neutral-grip-lat-pulldown',
    name: 'Close Neutral Grip Lat Pulldown',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    muscleBias: 'lats_upper',
    equipment: ['cable', 'machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Neutral grip (palms facing)', 'Pull elbows down', 'Minimize arm involvement'],
  },
  {
    id: 'bench-supported-db-row',
    name: 'Bench Supported Dumbbell Row',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Chest on bench', 'Pull dumbbell to hip', 'Squeeze shoulder blade'],
  },

  // TRAPS (3 exercises)
  {
    id: 'kelso-shrug-machine',
    name: 'Kelso Shrug Machine',
    movementPattern: 'trap_row',
    primaryMuscles: ['traps'],
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Upright posture', 'Shrug shoulders up', 'Full range of motion'],
  },
  {
    id: 'kelso-shrug-dumbbell',
    name: 'Kelso Shrug Dumbbell',
    movementPattern: 'trap_row',
    primaryMuscles: ['traps'],
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Upright posture', 'Shrug shoulders up', 'Control descent'],
  },
  {
    id: 'kelso-shrug-smith',
    name: 'Kelso Shrug Smith Machine',
    movementPattern: 'trap_row',
    primaryMuscles: ['traps'],
    equipment: ['smith_machine'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Upright stance', 'Shrug up maximally', 'Full range of motion'],
  },
  {
    id: 'chest-supported-upper-back-row',
    name: 'Chest Supported Upper Back Row',
    movementPattern: 'trap_row',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['back'],
    equipment: ['barbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'intermediate',
    techniqueCues: ['Chest on incline', 'Pull bar to chest', 'Squeeze traps'],
  },
  {
    id: 'db-bench-supported-upper-back-row',
    name: 'Dumbbell Bench Supported Upper Back Row',
    movementPattern: 'trap_row',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['back'],
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Chest on bench', 'Row dumbbells to chest', 'Squeeze traps and rhomboids'],
  },

  // BICEPS (5 exercises)
  {
    id: 'machine-preacher-curl',
    name: 'Machine Preacher Curl',
    movementPattern: 'elbow_flexion',
    primaryMuscles: ['biceps'],
    lengthTension: 'lengthened',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Arm fully extended at bottom', 'Curl to top', 'Squeeze at peak'],
  },
  {
    id: 'seated-curl-machine',
    name: 'Seated Curl Machine',
    movementPattern: 'elbow_flexion',
    primaryMuscles: ['biceps'],
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Seated position', 'Full range of motion', 'Squeeze at top'],
  },
  {
    id: 'db-preacher-curl',
    name: 'Dumbbell Preacher Curl',
    movementPattern: 'elbow_flexion',
    primaryMuscles: ['biceps'],
    lengthTension: 'lengthened',
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Forearms fully extended', 'Curl to top', 'Control descent'],
  },
  {
    id: 'db-curl',
    name: 'Dumbbell Curl',
    movementPattern: 'elbow_flexion',
    primaryMuscles: ['biceps'],
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Supinated grip', 'Control eccentric phase', 'Avoid swinging'],
  },
  {
    id: 'cable-curl',
    name: 'Cable Curl',
    movementPattern: 'elbow_flexion',
    primaryMuscles: ['biceps'],
    equipment: ['cable'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Keep elbows fixed', 'Curl rope or bar', 'Constant tension'],
  },

  // TRICEPS (6 exercises)
  {
    id: 'cable-unilateral-extension',
    name: 'Cable Unilateral Extension',
    movementPattern: 'elbow_extension',
    primaryMuscles: ['triceps'],
    equipment: ['cable'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['One arm at a time', 'Extend fully', 'Control the eccentric'],
  },
  {
    id: 'cable-extensions',
    name: 'Cable Extensions',
    movementPattern: 'elbow_extension',
    primaryMuscles: ['triceps'],
    equipment: ['cable'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Elbows fixed at sides', 'Extend fully', 'Constant tension'],
  },
  {
    id: 'cable-overhead-extensions',
    name: 'Cable Overhead Extensions',
    movementPattern: 'elbow_extension',
    primaryMuscles: ['triceps'],
    muscleBias: 'triceps_long',
    lengthTension: 'lengthened',
    equipment: ['cable'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Rope or cable overhead', 'Elbows shoulder-width', 'Full extension'],
  },
  {
    id: 'machine-dip',
    name: 'Machine Dip',
    movementPattern: 'elbow_extension',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest'],
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Full range of motion', 'Controlled descent', 'Lean slightly forward'],
  },
  {
    id: 'jm-press',
    name: 'JM Press',
    movementPattern: 'vertical_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['barbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'intermediate',
    techniqueCues: ['Hands at shoulder width', 'Press at angle', 'Full range of motion'],
  },
  {
    id: 'db-overhead-extension',
    name: 'Dumbbell Overhead Extension',
    movementPattern: 'elbow_extension',
    primaryMuscles: ['triceps'],
    muscleBias: 'triceps_long',
    lengthTension: 'lengthened',
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Dumbbell overhead', 'Elbows shoulder-width', 'Full extension'],
  },

  // SHOULDERS (7 exercises)
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    movementPattern: 'vertical_push',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    muscleBias: 'delts_front',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Shoulders pinned', 'Press straight up', 'Control lowering'],
  },
  {
    id: 'machine-lateral-raise',
    name: 'Machine Lateral Raise',
    movementPattern: 'shoulder_abduction',
    primaryMuscles: ['shoulders'],
    muscleBias: 'delts_lateral',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Slight elbow bend', 'Raise to shoulder height', 'Control the descent'],
  },
  {
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    movementPattern: 'shoulder_abduction',
    primaryMuscles: ['shoulders'],
    muscleBias: 'delts_lateral',
    equipment: ['cable'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'beginner',
    techniqueCues: ['Slight forward lean', 'Raise to shoulder height', 'One-armed or bilateral'],
  },
  {
    id: 'reverse-pec-deck',
    name: 'Reverse Pec Deck',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    muscleBias: 'delts_rear',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Chest up', 'Pull handles back', 'Shoulder blades together'],
  },
  {
    id: 'reverse-cable-fly',
    name: 'Reverse Cable Fly',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    muscleBias: 'delts_rear',
    equipment: ['cable'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Slight elbow bend', 'Fly handles back', 'Squeeze rear delts'],
  },
  {
    id: 'db-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    movementPattern: 'shoulder_abduction',
    primaryMuscles: ['shoulders'],
    muscleBias: 'delts_lateral',
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'low',
    experienceMin: 'beginner',
    techniqueCues: ['Slight elbow bend', 'Raise to shoulder height', 'Control descent'],
  },
  {
    id: 'db-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    movementPattern: 'vertical_push',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    muscleBias: 'delts_front',
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Dumbbells at shoulders', 'Press overhead', 'Control descent'],
  },
  {
    id: 'db-rear-delt-fly',
    name: 'Dumbbell Rear Delt Fly',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['shoulders'],
    muscleBias: 'delts_rear',
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'low',
    experienceMin: 'beginner',
    techniqueCues: ['Slight elbow bend', 'Fly dumbbells back', 'Feel rear delt contraction'],
  },

  // QUADS (6 exercises)
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    movementPattern: 'knee_extension',
    primaryMuscles: ['quads'],
    lengthTension: 'lengthened',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Back against pad', 'Extend fully', 'Control the descent'],
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'high',
    experienceMin: 'beginner',
    techniqueCues: ['Back against pad', 'Shoulders under handles', 'Full range of motion'],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'high',
    experienceMin: 'never',
    techniqueCues: ['Feet shoulder-width', 'Quarter to full squat', 'Controlled descent'],
  },
  {
    id: 'smith-squat',
    name: 'Smith Machine Squat',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['smith_machine'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'beginner',
    techniqueCues: ['Feet forward', 'Full range motion', 'Chest up'],
  },
  {
    id: 'barbell-squat',
    name: 'Barbell Squat',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['barbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'intermediate',
    techniqueCues: ['Shoulder-width stance', 'Chest up', 'Full range of motion'],
  },
  {
    id: 'split-squat',
    name: 'Split Squat',
    movementPattern: 'lunge',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['barbell', 'dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Front leg forward', 'Lower back knee', 'Upright torso'],
  },

  // HAMSTRINGS (4 exercises)
  {
    id: 'sldl-barbell',
    name: 'Stiff Leg Deadlift (Barbell)',
    movementPattern: 'hip_hinge',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'adductors'],
    lengthTension: 'lengthened',
    equipment: ['barbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'intermediate',
    techniqueCues: ['Hip hinge', 'Neutral spine', 'Stretch hamstring'],
  },
  {
    id: 'sldl-smith',
    name: 'Stiff Leg Deadlift (Smith Machine)',
    movementPattern: 'hip_hinge',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'adductors'],
    lengthTension: 'lengthened',
    equipment: ['smith_machine'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'beginner',
    techniqueCues: ['Hip hinge pattern', 'Controlled range', 'Feel hamstring stretch'],
  },
  {
    id: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    movementPattern: 'knee_flexion',
    primaryMuscles: ['hamstrings'],
    lengthTension: 'lengthened',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Hips on pad', 'Curl heels toward glutes', 'Control return'],
  },
  {
    id: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    movementPattern: 'knee_flexion',
    primaryMuscles: ['hamstrings'],
    lengthTension: 'mid_range',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Back against pad', 'Feet under pad', 'Curl with control'],
  },
  {
    id: '45-leg-extension',
    name: '45 Degree Leg Press Calf Raise',
    movementPattern: 'knee_flexion',
    primaryMuscles: ['hamstrings'],
    lengthTension: 'lengthened',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['45 degree angle', 'Controlled curl', 'Full range of motion'],
  },

  // GLUTES (4 exercises)
  {
    id: 'machine-hip-thrust',
    name: 'Machine Hip Thrust',
    movementPattern: 'hip_extension',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    lengthTension: 'shortened',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Full hip extension', 'Squeeze glutes', 'Controlled descent'],
  },
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    movementPattern: 'hip_extension',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    lengthTension: 'shortened',
    equipment: ['barbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'intermediate',
    techniqueCues: ['Back on bench', 'Full hip extension', 'Explosive thrust'],
  },
  {
    id: 'smith-hip-thrust',
    name: 'Smith Machine Hip Thrust',
    movementPattern: 'hip_extension',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    lengthTension: 'shortened',
    equipment: ['smith_machine'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Back on bench', 'Full hip extension', 'Glute squeeze'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    movementPattern: 'hip_hinge',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'adductors'],
    lengthTension: 'lengthened',
    equipment: ['barbell', 'dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'intermediate',
    techniqueCues: ['Slight knee bend', 'Hinge at hips', 'Feel hamstring stretch'],
  },
  {
    id: 'romanian-deadlift-smith',
    name: 'Romanian Deadlift (Smith Machine)',
    movementPattern: 'hip_hinge',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'adductors'],
    lengthTension: 'lengthened',
    equipment: ['smith_machine'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'beginner',
    techniqueCues: ['Slight knee bend', 'Hip hinge pattern', 'Full range of motion'],
  },

  // ADDUCTORS (1 exercise)
  {
    id: 'adductor-machine',
    name: 'Adductor Machine',
    movementPattern: 'adduction',
    primaryMuscles: ['adductors'],
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Legs together', 'Squeeze inward', 'Controlled return'],
  },

  // ABDUCTORS (1 exercise)
  {
    id: 'abductor-machine',
    name: 'Abductor Machine',
    movementPattern: 'abduction',
    primaryMuscles: ['abductors'],
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Start with legs together', 'Spread legs out', 'Controlled return'],
  },

  // ABS (3 exercises)
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    movementPattern: 'core_flexion',
    primaryMuscles: ['core'],
    equipment: ['cable'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Rope over shoulders', 'Crunch downward', 'Full contraction'],
  },
  {
    id: 'machine-crunch',
    name: 'Machine Crunch',
    movementPattern: 'core_flexion',
    primaryMuscles: ['core'],
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Back against pad', 'Crunch forward', 'Controlled return'],
  },
  {
    id: 'decline-crunch',
    name: 'Decline Crunch',
    movementPattern: 'core_flexion',
    primaryMuscles: ['core'],
    equipment: ['machine', 'bodyweight'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'low',
    experienceMin: 'beginner',
    techniqueCues: ['Decline bench 30-45 degrees', 'Crunch up', 'Controlled descent'],
  },

  // CALVES (4 exercises)
  {
    id: 'machine-calf-raise',
    name: 'Machine Calf Raise',
    movementPattern: 'calf_raise',
    primaryMuscles: ['calves'],
    lengthTension: 'shortened',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Shoulders under pads', 'Rise on toes', 'Full range of motion'],
  },
  {
    id: 'standing-calf-raise-machine',
    name: 'Standing Calf Raise',
    movementPattern: 'calf_raise',
    primaryMuscles: ['calves'],
    lengthTension: 'shortened',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Upright position', 'Rise on toes', 'Full stretch at bottom'],
  },
  {
    id: 'leg-press-calf-raise',
    name: 'Calf Raise on Leg Press Machine',
    movementPattern: 'calf_raise',
    primaryMuscles: ['calves'],
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Toes on platform', 'Press with calves', 'Full range of motion'],
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    movementPattern: 'calf_raise',
    primaryMuscles: ['calves'],
    lengthTension: 'shortened',
    equipment: ['machine'],
    gymTypes: ['commercial'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Full range of motion', 'Stretch at bottom', 'Full extension at top'],
  },
];

/**
 * Get exercises by movement pattern
 */
export function getExercisesByPattern(pattern: MovementPattern): CatalogExercise[] {
  return EXERCISE_CATALOG.filter((exercise) => exercise.movementPattern === pattern);
}

/**
 * Get exercises by muscle group
 */
export function getExercisesByMuscle(muscle: MuscleGroup): CatalogExercise[] {
  return EXERCISE_CATALOG.filter(
    (exercise) =>
      exercise.primaryMuscles.includes(muscle) ||
      exercise.secondaryMuscles?.includes(muscle),
  );
}

/**
 * Get exercises available for a specific gym type
 */
export function getExercisesForGym(gymType: GymType): CatalogExercise[] {
  return EXERCISE_CATALOG.filter((exercise) => exercise.gymTypes.includes(gymType));
}

/**
 * Get exercise by ID
 */
export function getExerciseById(id: string): CatalogExercise | undefined {
  return EXERCISE_CATALOG.find((exercise) => exercise.id === id);
}
