/**
 * Exercise Catalog
 * Curated database of 30-40 machine-focused exercises for hypertrophy training
 */

import type { CatalogExercise, GymType, MovementPattern, MuscleGroup } from './types';

/**
 * Complete exercise catalog - predominantly machines, covering all body parts
 */
export const EXERCISE_CATALOG: CatalogExercise[] = [
  // CHEST (5 exercises)
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'high',
    experienceMin: 'never',
    techniqueCues: ['Keep back firmly against pad', 'Press straight, not angled', 'Full range of motion'],
  },
  {
    id: 'pec-deck',
    name: 'Pec Deck',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Chest up, shoulders depressed', 'Squeeze handles together', 'Control the stretch'],
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Slight bend in elbows', 'Bring hands together at midline', 'Control eccentric phase'],
  },
  {
    id: 'smith-bench-press',
    name: 'Smith Machine Bench Press',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['smith_machine'],
    gymTypes: ['commercial', 'hotel', 'home'],
    taxingness: 'high',
    experienceMin: 'beginner',
    techniqueCues: ['Neutral grip or slightly angled', 'Full depth stretch', 'Control the bar'],
  },
  {
    id: 'incline-machine-press',
    name: 'Incline Machine Press',
    movementPattern: 'vertical_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    muscleBias: 'chest_upper',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'high',
    experienceMin: 'never',
    techniqueCues: ['Shoulders pinned back', 'Press in straight line', 'Controlled descent'],
  },

  // BACK (5 exercises)
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    muscleBias: 'lats_lower',
    equipment: ['cable', 'machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Chest up', 'Pull elbows down', 'Full stretch at top'],
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Chest forward', 'Pull to torso', 'Squeeze shoulder blades'],
  },
  {
    id: 'machine-row',
    name: 'Machine Row',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Chest against pad', 'Pull handles to body', 'Control return'],
  },
  {
    id: 'cable-pullover',
    name: 'Cable Pullover',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['chest'],
    lengthTension: 'lengthened',
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'beginner',
    techniqueCues: ['Slight elbow bend', 'Pull down and back', 'Full stretch at top'],
  },
  {
    id: 'underhand-lat-pulldown',
    name: 'Underhand Lat Pulldown',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    muscleBias: 'lats_upper',
    equipment: ['cable', 'machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Shoulders depressed', 'Pull elbows back', 'Minimize arm involvement'],
  },

  // SHOULDERS (5 exercises)
  {
    id: 'lateral-raise-machine',
    name: 'Lateral Raise Machine',
    movementPattern: 'shoulder_abduction',
    primaryMuscles: ['shoulders'],
    muscleBias: 'delts_lateral',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Slight elbow bend', 'Raise to shoulder height', 'Control the descent'],
  },
  {
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    movementPattern: 'shoulder_abduction',
    primaryMuscles: ['shoulders'],
    muscleBias: 'delts_lateral',
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'beginner',
    techniqueCues: ['Slight forward lean', 'Raise to shoulder height', 'One-armed or bilateral'],
  },
  {
    id: 'reverse-pec-deck',
    name: 'Reverse Pec Deck',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    muscleBias: 'delts_rear',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Chest up', 'Pull handles back', 'Shoulder blades together'],
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    movementPattern: 'vertical_push',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    muscleBias: 'delts_front',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'high',
    experienceMin: 'never',
    techniqueCues: ['Shoulders pinned', 'Press straight up', 'Control lowering'],
  },
  {
    id: 'cable-shoulder-press',
    name: 'Cable Shoulder Press',
    movementPattern: 'vertical_push',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Stand tall', 'Press overhead', 'Slight forward angle acceptable'],
  },

  // BICEPS (4 exercises)
  {
    id: 'machine-preacher-curl',
    name: 'Machine Preacher Curl',
    movementPattern: 'elbow_flexion',
    primaryMuscles: ['biceps'],
    lengthTension: 'lengthened',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Arm fully extended at bottom', 'Curl to top', 'Squeeze at peak'],
  },
  {
    id: 'cable-curl',
    name: 'Cable Curl',
    movementPattern: 'elbow_flexion',
    primaryMuscles: ['biceps'],
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Keep elbows fixed', 'Curl rope or bar', 'Constant tension'],
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    movementPattern: 'elbow_flexion',
    primaryMuscles: ['biceps'],
    equipment: ['dumbbell'],
    gymTypes: ['commercial', 'home', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Neutral or supinated grip', 'Control eccentric', 'Avoid swinging'],
  },
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    movementPattern: 'elbow_flexion',
    primaryMuscles: ['biceps'],
    equipment: ['barbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'intermediate',
    techniqueCues: ['Shoulder-width grip', 'Full range', 'No momentum'],
  },

  // TRICEPS (5 exercises)
  {
    id: 'cable-pushdown',
    name: 'Cable Pushdown',
    movementPattern: 'elbow_extension',
    primaryMuscles: ['triceps'],
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Elbows fixed at sides', 'Extend fully', 'Control the stretch'],
  },
  {
    id: 'machine-dip',
    name: 'Machine Dip',
    movementPattern: 'elbow_extension',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest'],
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'high',
    experienceMin: 'never',
    techniqueCues: ['Full range of motion', 'Controlled descent', 'Lean slightly forward'],
  },
  {
    id: 'overhead-cable-extension',
    name: 'Overhead Cable Extension',
    movementPattern: 'elbow_extension',
    primaryMuscles: ['triceps'],
    muscleBias: 'triceps_long',
    lengthTension: 'lengthened',
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Rope or cable overhead', 'Elbows shoulder-width', 'Full extension'],
  },
  {
    id: 'machine-triceps-press',
    name: 'Machine Triceps Press',
    movementPattern: 'elbow_extension',
    primaryMuscles: ['triceps'],
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Seated position', 'Press handles away', 'Return with control'],
  },
  {
    id: 'rope-overhead-extension',
    name: 'Rope Overhead Extension',
    movementPattern: 'elbow_extension',
    primaryMuscles: ['triceps'],
    muscleBias: 'triceps_long',
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Rope overhead', 'Extend fully', 'Feel the stretch'],
  },

  // QUADS (5 exercises)
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    movementPattern: 'knee_extension',
    primaryMuscles: ['quads'],
    lengthTension: 'lengthened',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Back against pad', 'Extend fully', 'Control the descent'],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes', 'hamstrings'],
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'high',
    experienceMin: 'never',
    techniqueCues: ['Feet shoulder-width', 'Quarter to full squat', 'Controlled descent'],
  },
  {
    id: 'smith-squat',
    name: 'Smith Machine Squat',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes', 'hamstrings'],
    equipment: ['smith_machine'],
    gymTypes: ['commercial', 'hotel', 'home'],
    taxingness: 'high',
    experienceMin: 'beginner',
    techniqueCues: ['Feet forward', 'Full range motion', 'Chest up'],
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'high',
    experienceMin: 'beginner',
    techniqueCues: ['Back against pad', 'Shoulders under handles', 'Full range of motion'],
  },
  {
    id: 'machine-leg-press-v2',
    name: 'Machine Leg Press (V2)',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes', 'hamstrings'],
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'high',
    experienceMin: 'never',
    techniqueCues: ['Adjust seat position', 'Press through midfoot', 'Full range'],
  },

  // HAMSTRINGS (5 exercises)
  {
    id: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    movementPattern: 'knee_flexion',
    primaryMuscles: ['hamstrings'],
    lengthTension: 'lengthened',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Hips on pad', 'Curl heels toward glutes', 'Control return'],
  },
  {
    id: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    movementPattern: 'knee_flexion',
    primaryMuscles: ['hamstrings'],
    lengthTension: 'mid_range',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'never',
    techniqueCues: ['Back against pad', 'Feet under pad', 'Curl with control'],
  },
  {
    id: 'sldl-barbell',
    name: 'Single Leg Deadlift (Barbell)',
    movementPattern: 'hip_hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['back'],
    lengthTension: 'lengthened',
    equipment: ['barbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'intermediate',
    techniqueCues: ['Hip hinge', 'Neutral spine', 'Stretch hamstring'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    movementPattern: 'hip_hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['back'],
    lengthTension: 'lengthened',
    equipment: ['barbell', 'dumbbell'],
    gymTypes: ['commercial', 'home'],
    taxingness: 'high',
    experienceMin: 'beginner',
    techniqueCues: ['Slight knee bend', 'Hinge at hips', 'Feel hamstring stretch'],
  },
  {
    id: 'nordic-curl',
    name: 'Nordic Curl',
    movementPattern: 'knee_flexion',
    primaryMuscles: ['hamstrings'],
    lengthTension: 'lengthened',
    equipment: ['bodyweight'],
    gymTypes: ['commercial', 'hotel', 'home'],
    taxingness: 'high',
    experienceMin: 'intermediate',
    techniqueCues: ['Slow eccentric', 'Use hands minimally', 'Full range'],
  },

  // GLUTES (4 exercises)
  {
    id: 'hip-thrust-machine',
    name: 'Hip Thrust Machine',
    movementPattern: 'hip_hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    lengthTension: 'shortened',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'high',
    experienceMin: 'never',
    techniqueCues: ['Full hip extension', 'Squeeze glutes', 'Controlled descent'],
  },
  {
    id: 'cable-pull-through',
    name: 'Cable Pull-Through',
    movementPattern: 'hip_hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    lengthTension: 'lengthened',
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'moderate',
    experienceMin: 'beginner',
    techniqueCues: ['Hip hinge', 'Stand tall', 'Glute contraction at top'],
  },
  {
    id: 'glute-kickback-machine',
    name: 'Glute Kickback Machine',
    movementPattern: 'hip_hinge',
    primaryMuscles: ['glutes'],
    lengthTension: 'shortened',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Extend leg back', 'Squeeze glutes', 'Control return'],
  },
  {
    id: 'smith-hip-thrust',
    name: 'Smith Machine Hip Thrust',
    movementPattern: 'hip_hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    lengthTension: 'shortened',
    equipment: ['smith_machine'],
    gymTypes: ['commercial', 'hotel', 'home'],
    taxingness: 'high',
    experienceMin: 'beginner',
    techniqueCues: ['Back on bench', 'Full hip extension', 'Glute squeeze'],
  },

  // CALVES (3 exercises)
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    movementPattern: 'calf_raise',
    primaryMuscles: ['calves'],
    lengthTension: 'shortened',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Full range of motion', 'Stretch at bottom', 'Full extension at top'],
  },
  {
    id: 'standing-calf-raise-machine',
    name: 'Standing Calf Raise Machine',
    movementPattern: 'calf_raise',
    primaryMuscles: ['calves'],
    lengthTension: 'shortened',
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Shoulders under pads', 'Rise on toes', 'Full range of motion'],
  },
  {
    id: 'calf-press-machine',
    name: 'Calf Press (Machine)',
    movementPattern: 'calf_raise',
    primaryMuscles: ['calves'],
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Toes on platform', 'Press with calves', 'Full range of motion'],
  },

  // CORE (3 exercises)
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    movementPattern: 'core_flexion',
    primaryMuscles: ['core'],
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Rope over shoulders', 'Crunch downward', 'Full contraction'],
  },
  {
    id: 'machine-crunch',
    name: 'Machine Crunch',
    movementPattern: 'core_flexion',
    primaryMuscles: ['core'],
    equipment: ['machine'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'never',
    techniqueCues: ['Back against pad', 'Crunch forward', 'Controlled return'],
  },
  {
    id: 'cable-rotation',
    name: 'Cable Rotation',
    movementPattern: 'core_rotation',
    primaryMuscles: ['core'],
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'beginner',
    techniqueCues: ['Stand perpendicular', 'Rotate with cable', 'Full range rotation'],
  },

  // FOREARMS (2 exercises)
  {
    id: 'cable-wrist-curl',
    name: 'Cable Wrist Curl',
    movementPattern: 'elbow_flexion',
    primaryMuscles: ['forearms'],
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'beginner',
    techniqueCues: ['Forearms on pad', 'Curl with wrists', 'Control the weight'],
  },
  {
    id: 'reverse-cable-curl',
    name: 'Reverse Cable Curl',
    movementPattern: 'elbow_flexion',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    gymTypes: ['commercial', 'hotel'],
    taxingness: 'low',
    experienceMin: 'beginner',
    techniqueCues: ['Overhand grip', 'Extend wrists', 'Control the motion'],
  },
];

/**
 * Get exercises by movement pattern
 */
export function getExercisesByPattern(pattern: MovementPattern): CatalogExercise[] {
  return EXERCISE_CATALOG.filter((exercise) => exercise.movementPattern === pattern);
}

/**
 * Get exercises by muscle group
 */
export function getExercisesByMuscle(muscle: MuscleGroup): CatalogExercise[] {
  return EXERCISE_CATALOG.filter(
    (exercise) =>
      exercise.primaryMuscles.includes(muscle) ||
      exercise.secondaryMuscles?.includes(muscle),
  );
}

/**
 * Get exercises available for a specific gym type
 */
export function getExercisesForGym(gymType: GymType): CatalogExercise[] {
  return EXERCISE_CATALOG.filter((exercise) => exercise.gymTypes.includes(gymType));
}

/**
 * Get exercise by ID
 */
export function getExerciseById(id: string): CatalogExercise | undefined {
  return EXERCISE_CATALOG.find((exercise) => exercise.id === id);
}
